{ ... }:

{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    # Genera el formato .lua directamente
    configType = "lua";

    extraConfig = ''
      -- Desactivar el aviso de archivo autogenerado
      hl.config({ autogenerated = false })

      hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
      hl.env("HYPRCURSOR_SIZE","24")
      hl.env("XCURSOR_THEME","Bibata-Modern-Ice")
      hl.env("XCURSOR_SIZE","24")

      hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")

      local active_border_color = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 }
      local inactive_border_color = "rgba(595959aa)"

      -- =========================================================================
      -- TABLA GLOBAL DE CONFIGURACIÓN
      -- =========================================================================
      local config = {
        monitor = {
          ", preferred, auto, 1"
        },
        general = {
          gaps_in = 1,
          gaps_out = 1,
          border_size = 1,

          col = {
            active_border = active_border_color,
            inactive_border = inactive_border_color,
          },

          resize_on_border = true,
          layout = "dwindle"
        },

        decoration = {
          rounding = 0,

    		  -- Change transparency of focused and unfocused windows
    		  active_opacity = 1.0,
    		  inactive_opacity = 1.0,

    		  shadow = {
    		    enabled = true,
    		    range = 4,
    		    render_power = 3,
    		    color = "rgba(1a1a1aee)",
    		  },

          blur = {
            enabled = true,
            size = 3,
            passes = 1,

            vibrancy = 0.1696,
          }
        } -- decoration
      } -- local config

    -- Registrar la tabla en el compositor:
    hl.config(config)

    hl.config({
        dwindle = {
            -- Habilita preserve_split para que la funcion togglesplit tenga efecto
            preserve_split = true
        }
    })

	  hl.config({
			-- ESTILO PARA GRUPOS ROBADO DE OMARCHY
			-- https://github.com/omacom/omarchy/raw/5ead870507dfb68db696b3ddb948cc3d178e8d62/default/hypr/looknfeel.lua
  	  group = {
        col = {
          border_active = active_border_color,
          border_inactive = inactive_border_color,
        },

        groupbar = {
          font_size = 12,
          font_family = "monospace",
          font_weight_active = "ultraheavy",
          font_weight_inactive = "normal",
          indicator_height = 1,
          indicator_gap = 5,
          height = 22,
          gaps_in = 5,
          gaps_out = 0,
          text_color = "rgb(ffffff)",
          text_color_inactive = "rgba(ffffff90)",
          col = {
            active = "rgba(00000040)",
            inactive = "rgba(00000020)",
          },
          gradients = true,
          gradient_rounding = 0,
          gradient_round_only_edges = false,
        }, -- groupbar
      }, -- group

	    input = {
	      numlock_by_default = true,
	      kb_layout = "us",
	      kb_variant = "altgr-intl",
	      follow_mouse = 1,
	      sensitivity = 0,
	      touchpad = {
	        natural_scroll = false,
	      },
	    }
	  })

    -- =========================================================================
    -- AUTOSTART: Evento oficial de inicio asíncrono
    -- =========================================================================
    hl.on("hyprland.start", function()
      hl.exec_cmd("quickshell")
      hl.exec_cmd("mako")
      hl.exec_cmd("clipse -listen")
      hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    end)

    -- =========================================================================
    -- ASIGNACIÓN DE ATAJOS DE TECLADO
    -- =========================================================================
    local terminal = "kitty"
    local menu = "wofi --show drun"
    local mainMod = "SUPER"

    -- Aplicaciones y acciones de sistema
    hl.bind("SUPER + RETURN", hl.dsp.exec_cmd(terminal))
    hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd("kitty --title float_term"))
    hl.bind("SUPER + Q", hl.dsp.window.close())
    hl.bind("SUPER + M", hl.dsp.exit())
    hl.bind("SUPER + N", hl.dsp.exec_cmd("nautilus"))
    hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
    hl.bind("SUPER + SPACE", hl.dsp.exec_cmd(menu))
    hl.bind("SUPER + E ", hl.dsp.exec_cmd("gnome-text-editor"))
    hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("kitty --title kitty-clipse -e clipse"))
    hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock --grace 5"))

    -- Screenshots
    hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m region -o " .. os.getenv("HOME") .. "/Imágenes/Screenshots"))
    hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m output -o " .. os.getenv("HOME") .. "/Imágenes/Screenshots"))

    -- Navegación de foco usando la API estructurada direction
    hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
    hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
    hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
    hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))

    -- Switch workspaces with mainMod + [0-9]
    hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = "1" }))
    hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = "2" }))
    hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = "3" }))
    hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = "4" }))
    hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = "5" }))
    hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = "6" }))
    hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = "7" }))
    hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = "8" }))
    hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = "9" }))
    hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = "10" }))

    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
    hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
    hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
    hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
    hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
    hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
    hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
    hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
    hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
    hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))

	  -- Moverse entre workspaces con CTRL + ALT + Flechas
	  hl.bind("CTRL + ALT + RIGHT", hl.dsp.focus({ workspace = "e+1" }))
	  hl.bind("CTRL + ALT + LEFT", hl.dsp.focus({ workspace = "e-1" }))

    -- Laptop multimedia keys for volume and LCD brightness
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })
    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })
    hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })
    hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { repeating = true, locked = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { repeating = true, locked = true })

    -- Requires playerctl
    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

    -- BINDINGS ROBADOS DE OMARCHY
    -- https://github.com/omacom/omarchy/raw/refs/heads/quattro/default/hypr/bindings/tiling.lua
    hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
    hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

    -- Alterna layout entre dwindle y scrolling
    hl.bind("SUPER + tab", function ()
        local layouts = { "scrolling", "dwindle" }
        local workspace = hl.get_active_workspace()
        if not workspace then return end

        local next_layout = "dwindle"
        for i = 1, #layouts do
            if layouts[i] == workspace.tiled_layout then
                next_layout = layouts[(i % #layouts) + 1]
                break
            end
        end

        hl.workspace_rule({ workspace = tostring(workspace.id), layout = next_layout })
        hl.dispatch(hl.dsp.exec_cmd("notify-send 'Hyprland' '󱂬 Cambio de Layout: " .. next_layout .. "'"))

    end)

    -- SCROLLEAR WORKSPACES
    hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

    -- "Move window" mouse:272 = botón izquierdo del ratón
    hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
    -- "Resize window" mouse:273 = botón derecho del ratón
    hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

    --"Toggle scratchpad"
    hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("scratchpad"))
    -- "Move window to scratchpad"
    hl.bind("SUPER + ALT + S", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))

    -- "Swap window to the left"
    hl.bind("SUPER + SHIFT + LEFT", hl.dsp.window.swap({ direction = "l" }))
    -- "Swap window to the right"
    hl.bind("SUPER + SHIFT + RIGHT", hl.dsp.window.swap({ direction = "r" }))
    -- "Swap window up"
    hl.bind("SUPER + SHIFT + UP", hl.dsp.window.swap({ direction = "u" }))
    -- "Swap window down"
    hl.bind("SUPER + SHIFT + DOWN", hl.dsp.window.swap({ direction = "d" }))

    -- GROUPING
    -- "Toggle window grouping"
    hl.bind("SUPER + G", hl.dsp.group.toggle())
    -- "Move active window out of group"
    hl.bind("SUPER + ALT + G", hl.dsp.window.move({ out_of_group = true }))

    -- "Move grouped window focus left"
    hl.bind("SUPER + CTRL + LEFT", hl.dsp.group.prev())
    -- "Move grouped window focus right"
    hl.bind("SUPER + CTRL + RIGHT", hl.dsp.group.next())

    -- REGLAS PARA VENTANAS
    -- REGLA PARA LA TERMINAL FLOTANTE
    hl.window_rule({
      match =  { title = "^(float_term)" },
      float = true,
      size = "(monitor_w*0.8) (monitor_h*0.8)"
    })

    -- REGLA PARA CLIPSE
    hl.window_rule({
        match = { title = "^(kitty-clipse)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.6)"
    })

    -- REGLA CALCULADORA
    hl.window_rule({
        match = { class = "^(org.gnome.Calculator)$" },
        float = true,
        size = "(monitor_w*0.4) (monitor_h*0.6)",
        opacity = "0.9 override 0.8 override 1.0 override"
    })

    -- REGLA CLIMA
    hl.window_rule({
        match = { class = "^(org.gnome.Weather)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.8)",
        opacity = "0.9 override 0.8 override 1.0 override"
    })

    -- REGLA CALENDAR
    hl.window_rule({
        match = { class = "^(org.gnome.Calendar)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.8)",
        opacity = "0.9 override 0.8 override 1.0 override"
    })

    -- REGLA PARA VOLUMEN Y BLUETOOTH
    hl.window_rule({
        match = { class = "^(org.pulseaudio.pavucontrol)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.8)"
    })

    hl.window_rule({
        match = { class = "^(blueman-manager)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.6)"
    })

    -- REGLA PARA EL PREVIEW DE NAUTILUS
    hl.window_rule({
        match = { class = "^(org\\.gnome\\.NautilusPreviewer)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.8)",
        opacity = "0.9 override 0.8 override 1.0 override"
    })

    -- REGLA PARA MODALS GTK?
    hl.window_rule({
        match = { class = "^(xdg-desktop-portal-gtk)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.6)"
    })

    -- REGLA PARA MODAL PICK A FILE
    hl.window_rule({
        match = { title = "^(Pick a file)$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.6)"
    })

    -- REGLA PARA LOGIN DE GOOGLE
    hl.window_rule({
        match = { title = "^(Acceso:\\sCuentas\\sde\\sGoogle(.*))$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.6)"
    })

    hl.window_rule({
        match = { title = "^(Sign\\sIn\\s-\\sGoogle\\sAccounts(.*))$" },
        float = true,
        size = "(monitor_w*0.7) (monitor_h*0.6)"
    })

    -- Set opacity to 0.9 (active), 0.8 (inactive), and 1.0 (fullscreen) for Nautilus
    hl.window_rule({
        match = { class = "org.gnome.Nautilus" },
        opacity = "0.9 override 0.8 override 1.0 override",
    })

    -- ANIMACIONES ROBADAS DE OMARCHY
    -- https://github.com/omacom/omarchy/raw/5ead870507dfb68db696b3ddb948cc3d178e8d62/default/hypr/looknfeel.lua
    hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
    hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
    hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
    hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
    hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

    hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
    hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windows", enabled = true, speed = 3.79, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
    hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
    hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
    hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
    hl.animation({ leaf = "fadeSwitch", enabled = false })
    hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
    hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
    hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
    hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
    hl.animation({ leaf = "workspaces", enabled = false })

    -- Monitores
    hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "1536x0", scale = 1.20 })
    hl.monitor({ output = "HDMI-A-2", mode = "1920x1080@60.00", position = "3146x0", scale = 1.20, transform = 3 })
    hl.monitor({ output = "HDMI-A-3", mode = "2560x1080@60.00", position = "1088x929", scale = 1.25 })

    -- HDMI-A-1: workspaces 1, 2, 3
    hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1" })
    hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1" })
    hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1" })

    -- HDMI-A-3: workspaces 4, 5, 6
    hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-3" })
    hl.workspace_rule({ workspace = "5", monitor = "HDMI-A-3" })
    hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-3" })

    -- HDMI-A-2: workspaces 7, 8, 9
    hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-2" })
    hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-2" })
    hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-2" })

    '';
  };
}
