#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/mypanels/launch.sh 2>~/.config/polybar/.polybar.err &
#pulseaudio &
nitrogen --restore &
picom -f &
gnome-keyring-daemon --start --components=pkcs11 &

bspc monitor DP-3 -d I II III IV V
bspc monitor HDMI-3 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#21a398"
bspc config presel_feedback_color "#a1ff59"

# move focus by moving mouse over them.
bspc config focus_follows_pointer   true
bspc config click_to_focus          true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a gedit desktop='^2'
bspc rule -a Nautilus state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
