#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
$HOME/.config/polybar/launch.sh --panels
pulseaudio &
nitrogen /usr/share/backgrounds/archlinux/wave.png --set-zoom-fill &
picom -f &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a gedit desktop='^2'
bspc rule -a Nautilus state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
