# Apps al iniciar
windowrule {
  name = windowrule-1
  workspace = 1
  match:class = ^(zen)$
}


# Regla para la ventana flotante de Clipse
windowrule {
  name = windowrule-2
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:title = ^(kitty-clipse)$
}


# Regla para la terminal flotante
windowrule {
  name = windowrule-3
  float = on
  center = on
  size = (monitor_w*0.8) (monitor_h*0.8)
  match:title = ^(float_term)$
}


windowrule {
  name = windowrule-4
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:title = ^(Acceso:\sCuentas\sde\sGoogle(.*))$
}


windowrule {
  name = windowrule-5
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:title = ^(Sign\sIn\s-\sGoogle\sAccounts(.*))$
}


# Regla para la ventana flotante del previsualizador de Nautilus
windowrule {
  name = windowrule-6
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.8)
  match:class = ^(org\.gnome\.NautilusPreviewer)$
}


# Regla para modals gtk?
windowrule {
  name = windowrule-7
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:class = ^(xdg-desktop-portal-gtk)$
}


# Regla para modal Pick a file
windowrule {
  name = windowrule-8
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:title = ^(Pick a file)$
}


# Bluetooth manager
windowrule {
  name = windowrule-9
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.6)
  match:class = ^(blueman-manager)$
}


# Regla para WhatsApp Web
windowrule {
  name = windowrule-10
  workspace = 7
  float = on
  size = (monitor_w*1) (monitor_h*0.5)
  move = (0) (0)
  match:class = ^(chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default)$
}


# Regla para WhatsApp Web
windowrule {
  name = windowrule-11
  float = on
  center = on
  size = (monitor_w*0.5) (monitor_h*0.9)
  match:class = ^(chrome-eohjpbkgbjejpphdmppimiodggipfole-Default)$
}


# Regla para btop abajo de whatsapp
windowrule {
  name = windowrule-12
  workspace = 7
  float = on
  size = (monitor_w*1) (monitor_h*0.5)
  move = ((monitor_w*0)) ((monitor_h*0.5))
  match:title = ^(kitty-btop)$
}


# Regla para Slack
windowrule {
  name = windowrule-13
  workspace = 8
  size = (monitor_w*1) (monitor_h*0.5)
  move = (0) (0)
  match:class = ^(Slack)$
}


# Regla para Pulseaudio
windowrule {
  name = windowrule-14
  float = on
  center = on
  size = 70% 80%
  match:class = ^(org.pulseaudio.pavucontrol)$
}


# Regla para Calculadora
windowrule {
  name = windowrule-15
  float = on
  center = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  match:class = ^(org.gnome.Calculator)$
}


# Regla para la Github Desktop flotante
windowrule {
  name = windowrule-16
  float = on
  center = on
  size = (monitor_w*0.8) (monitor_h*0.8)
  match:title = ^(GitHub Desktop)$
}


# Regla para Debug en Goland
windowrule {
  name = windowrule-17
  workspace = 5
  move = ((monitor_w*0)) ((monitor_h*0))
  size = (monitor_w*0.5) (monitor_h*1)
  match:title = ^(Debug - (.*))$
}

windowrule {
  name = windowrule-18
  float = on
  match:title = ^(Debug  - (.*))$
}


# Regla para Services en Goland
windowrule {
  name = windowrule-19
  workspace = 5
  move = ((monitor_w*0.5)) ((monitor_h*0))
  size = (monitor_w*0.5) (monitor_h*1)
  match:title = ^(Services - bridge)$
}

# windowrulev2 = float, title:^(Services - bridge)$

# Para Irium Webcam
windowrule {
  name = windowrule-20
  float = on
  center = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  match:class = ^(iriunwebcam)$
}

